### ISSUE TITLE
How to get forum.image.sc API key?

### ISSUE THREAD

**Issue by kephale** [ctrueden/monoqueue#1]
It seems like https://forum.image.sc/admin/api/keys may not be publicly available. 

<img width="766" alt="image" src="https://user-images.githubusercontent.com/400105/235301708-6e1143fb-89b7-45f7-82fb-141b2f01b8ae.png">

**Comment by kephale** [comment]
https://observablehq.com/@beanow/generate-user-api-key-for-discourse

[edit]
Follow up:

When using a user API key and running `mq up` I get:

`requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://forum.image.sc/search.json?q=%23development+tags%3Anapari%2Csciview%2Cpython%2Cscikit-image+status%3Aopen+status%3Aunsolved&page=1`

That URL does work in my browser that is already logged into the forum.

**Comment by ctrueden** [comment]
@kephale Thanks for playing with my toy. :smile_cat: 

I am not an expert on Discourse API keys, but I did generate a new read-only key for forum.image.sc with all user scope (instead of just me), and tested just now that it works. It's not clear to me whether posting the key publicly here would be a problem? For now, I PMed it to you on the forum.

**Comment by kephale** [comment]
Awesome! That works, thank you! 

It seems pretty cool. I'm excited to tweak my config some more.
